### ISSUE TITLE
FloatingLayout.CallBack() not found

### ISSUE THREAD

**Issue by soumoq** [HamedTaherpour/floating-layout-android#3]
//not found FloatingLayout.CallBack()  in kt file

FloatingLayout floatingLayout = new FloatingLayout(this, R.layout.floating_layout, new FloatingLayout.CallBack() { 
    @Override
    public void onClickListener(int resourceId) {
    
    }

    @Override
    public void onCreateListener(View view) {
    }
    
    @Override
    public void onCloseListener() {
    
    }
});

**Comment by HamedTaherpour** [comment]
fixed
